### ISSUE TITLE
Empty memory section doesn't update properly.

### ISSUE THREAD

**Issue by Ben12345rocks** [tchristofferson/Config-Updater#1]
Default config had this:

    VoteCoolDownEndedReward: []

Turned into this:

    VoteCoolDownEndedReward: !!org.bukkit.configuration.MemorySection {}

As a result it caused a yml error.

**Comment by tchristofferson** [comment]
Reimport ConfigUpdater library if your using Maven, it is still using version 1.1-SNAPSHOT
