### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by PretzelJohn** [tchristofferson/Config-Updater#11]
When loading my plugin, I get the following error:
java.lang.NoClassDefFoundError: com/tchristofferson/configupdater/ConfigUpdater

This error is caused by ConfigUpdater not being included in the packaged jar. Here is my pom.xml:

`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.pretzel.dev</groupId>
    <artifactId>VillagerTradeLimiter</artifactId>
    <version>1.3.1</version>

    <properties>
        <java.version>1.8</java.version>
    </properties>

    <build>
        <sourceDirectory>src</sourceDirectory>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <repositories>
        <repository>
            <id>spigotmc-repo</id>
            <url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
        </repository>
        <repository>
            <id>maven-central</id>
            <url>https://oss.sonatype.org/content/groups/public</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>org.spigotmc</groupId>
            <artifactId>spigot</artifactId>
            <version>1.17-R0.1-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.spigotmc</groupId>
            <artifactId>spigot-api</artifactId>
            <version>1.16.5-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.tchristofferson</groupId>
            <artifactId>ConfigUpdater</artifactId>
            <version>2.0-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>
</project>`

**Comment by FN-FAL113** [comment]
Relocate the shaded package

**Comment by tchristofferson** [comment]
Look into the Maven Shade plugin. There are many resources online that are available such as https://stackoverflow.com/questions/10568275/noclassdeffounderror-on-maven-dependency.
