### ISSUE TITLE
Deleted sections

### ISSUE THREAD

**Issue by realjackowl** [tchristofferson/Config-Updater#15]
```
      Ranges:
        '1':
          Action: ACTION
        '2':
          Action: ACTION
        '3':
          Action: ACTION
        '4':
          Action: ACTION
```

would become 

```
      Ranges:
```

**Comment by MetallicGoat** [comment]
> ```
>       Ranges:
>         '1':
>           Action: ACTION
>         '2':
>           Action: ACTION
>         '3':
>           Action: ACTION
>         '4':
>           Action: ACTION
> ```
> 
> would become
> 
> ```
>       Ranges:
> ```

Then tell the config manager to ignore that configuration section......

**Comment by jackowldev** [comment]
Yes, I could do that, but I want to update the old configs. It leads to this issue and I think that it's worth noting it doesn't work as it should.

**Comment by tchristofferson** [comment]
I can take a look at this at some point. The section should be deleted if it is removed from the default config (resource in the jar).

**Comment by realjackowl** [comment]
The issue seems to be with '.

**Comment by tchristofferson** [comment]
@realjackowl  What version of Spigot are you using? I am noticing a weird bug where if I do config.load(file) it doesn't actually load the file on 1.8.8. However, in 1.18.1 it works correctly. In 1.8.8 If instead of config.load(file) I do config = YamlConfiguration.load(file) it works.

**Comment by realjackowl** [comment]
@tchristofferson Paper 1.18.1.

**Comment by tchristofferson** [comment]
In my test I added in commit 7741c33957d5b08ddb15f0fbf91fdf5cc731f263 the removed section is deleted after calling the update method.

**Comment by owljackob** [comment]
That's the problem because the section wasn't deleted from updated config, it was only edited... but updating that removed it.
