### ISSUE TITLE
Configurationsection not being ignored correctly

### ISSUE THREAD

**Issue by TheNickSkater** [tchristofferson/Config-Updater#2]
Screenshots:

Before I reload the Server (and also how it should look like): https://prnt.sc/piaj7f
After reload: https://prnt.sc/piaja3

Yes I added the "RegenRules" to the ignored list, and yes.. It keeps the section.. But it just moves it to the right and so destroys its function.

**Comment by tchristofferson** [comment]
Fixed in commit 0a048db007ce29b59ca9d1bdd7af6ade46ccab39

**Comment by tchristofferson** [comment]
Re-import maven dependency, the version is still 1.1-SNAPSHOT.
