### ISSUE TITLE
How to use with a folder?

### ISSUE THREAD

**Issue by ArikSquad** [tchristofferson/Config-Updater#23]
I get a java.lang.NullPointerException: null?
![image](https://user-images.githubusercontent.com/75741608/215523706-87cf8c8d-3411-4213-accf-590c9701d90b.png)

also I didn't find any socials to message you

**Comment by tchristofferson** [comment]
Can you add the exception? I can't tell what the issue is without it.

**Comment by tchristofferson** [comment]
If there is still an issue re-open this issue and provide exceptions.
