### ISSUE TITLE
German Umlauts

### ISSUE THREAD

**Issue by chris3105x** [tchristofferson/Config-Updater#3]
Hey!
Thank you very much for this ressource!
German umlauts like ä, ü, ö get replaced by question marks. (also chars like "»") How can I fix this?
Thank you!

Best regards,
Christian

**Comment by tchristofferson** [comment]
I can fix this later today. Currently, I am using FileWriter and BufferedWriter, so FileWriter uses the system default for encoding. I will have to switch it to use a FileOutputStream and use UTF-8.

**Comment by tchristofferson** [comment]
Should be fixed after commit dcac39f

**Comment by chris3105x** [comment]
Thank you so much!!!
