### ISSUE TITLE
Option for making some Edits Update but Not Remove New Sections

### ISSUE THREAD

**Issue by KojiV** [tchristofferson/Config-Updater#30]
It's hard to explain in the title, but basically with the config updater, any new sections made are removed, but I also want any sections that are in the file to update, so what are the odds of getting a update like that? (basically allowing for the creation of new sections but also allowing for the **updating** of existing sections)

Also side question what are the odds of getting a overwrite section? As in a section where instead of keeping the edited values it just straight overrides it like normal.

**Comment by tchristofferson** [comment]
Do you mean you want ignored sections to update? The purpose of an ignored section is that it is left alone. If this is what you mean this will not be implemented. Let me know if this is what you meant, I could be misinterpreting what you mean.

As far as the overwrite enhancement, this is something that can probably be done. Please create a new issue specifically for that enhancement.
