### ISSUE TITLE
What to put in 

### ISSUE THREAD

**Issue by kloppie74** [tchristofferson/Config-Updater#34]
ConfigUpdater.update(this, "Settings.yml", configFile, Arrays.asList(....));

What to place on the .... ?

**Comment by tchristofferson** [comment]
That is where ignored config sections go. Sometimes a user can add their own keys to the config and you don't want them to disappear. For example, if you have a default section like this:
```
items:
    item1:
        ...
    item2:
       ...
```
and a user changes it to this:
```
items:
    item1:
        ...
    item2:
       ...
    item3:
        ...
```
By default config updater will overwrite the second config back to the first. If you use add a "items" to the list of ignored sections the items section will not be overwritten back to default.
