### ISSUE TITLE
Allow UTF-8 Charset

### ISSUE THREAD

**Issue by JewishBanana** [tchristofferson/Config-Updater#35]
Not really an issue more of just an added bonus, I noticed that Chinese characters weren't being saved over from config updates and that's because when you are loading the current config you don't load it with UTF-8 charset. So to fix this just change this one line here:
`FileConfiguration currentConfig = YamlConfiguration.loadConfiguration(toUpdate);` at [this line](https://github.com/tchristofferson/Config-Updater/blob/88630d4b2f013e9f15f00ac0468f47abb2cf1ff0/src/main/java/com/tchristofferson/configupdater/ConfigUpdater.java#L32)
To this:
`FileConfiguration currentConfig = YamlConfiguration.loadConfiguration(new InputStreamReader(FileUtils.openInputStream(toUpdate), StandardCharsets.UTF_8));`
This uses the apache file utils class.

**Comment by 404forever1** [comment]
Can you make a fork and let us refer to it again? I found that the 1.12 version will be garbled

**Comment by 404forever1** [comment]
It will make the Chinese characters in the configuration file of the 1.12.2 server garbled. I don't know why. I used java8, 21 is normal, but 1.12 requires java8

**Comment by JewishBanana** [comment]
> It will make the Chinese characters in the configuration file of the 1.12.2 server garbled. I don't know why. I used java8, 21 is normal, but 1.12 requires java8

I don't really want to make a fork for such a small issue, if you just manually change the line yourself in your code it will not garble the Chinese characters through update calls.

**Comment by tchristofferson** [comment]
Can you provide examples of Chinese characters that are causing issues? I want to test before pushing to maven central. You can also test it using the develop branch.

**Comment by 404forever1** [comment]
> 您能提供导致问题的中文字符示例吗？我想在自动化到 Maven Central 之前进行测试。您也可以使用开发分支进行测试。

Using java8 1.12.2 Any Chinese character

**Comment by 404forever1** [comment]
![image](https://github.com/user-attachments/assets/73c23a72-ffa7-4ff9-b5e1-b02ced22a6f4)
![image](https://github.com/user-attachments/assets/a73eddb1-0804-4728-9db4-32d0acdb74dc)
![image](https://github.com/user-attachments/assets/84ebcfd0-4749-4483-91a3-dea616fab335)

I tried to build 2.2 but it didn't work. I don't know why. In fact, I built 2.1 and it didn't work either. The plugin just gave an error. If it's convenient, please build one and I'll give it a try.

**Comment by tchristofferson** [comment]
I have pushed 2.2-SNAPSHOT to maven central. Try using that and let me know if it is resolved.

**Comment by 404forever1** [comment]
![image](https://github.com/user-attachments/assets/65623e71-bcd9-4192-979e-11d52b2f6cd3)
Probably no repair

**Comment by 404forever1** [comment]
![image](https://github.com/user-attachments/assets/4d4c27f6-d4a5-4b72-ae0c-d873d8f884a1)
The configuration seems to be good, but the comments are still garbled

**Comment by 404forever1** [comment]
[test.zip](https://github.com/user-attachments/files/18226321/test.zip)
一个非常简单的测试插件，只会加载配置文件

**Comment by tchristofferson** [comment]
I pushed another update. Re-download 2.2-SNAPSHOT and try again and let me know. I modified it so it parses comments using utf 8.

**Comment by 404forever1** [comment]
fix

**Comment by tchristofferson** [comment]
> fix

It is working now?

**Comment by 404forever1** [comment]
> > fix
> 
> It is working now?

yes

**Comment by 404forever1** [comment]
![image](https://github.com/user-attachments/assets/f5924349-9487-4d25-b465-6268954d6c87)

**Comment by tchristofferson** [comment]
Thanks for the help guys!

**Comment by JewishBanana** [comment]
> Thanks for the help guys!

No worries bro! Amazing resource you made, I use it in all my plugins!
