### ISSUE TITLE
UTF-8 issues are not completely resolved

### ISSUE THREAD

**Issue by 404forever1** [tchristofferson/Config-Updater#38]
![image](https://github.com/user-attachments/assets/e6714a6b-3157-4e66-83c8-79d3b5bb237d)
Seems like it doesn't work properly in the child node
![image](https://github.com/user-attachments/assets/32b7e44c-ba7a-454c-a846-80d8556ef48d)

**Comment by 404forever1** [comment]
This should be due to forgetting the logical gap?

**Comment by tchristofferson** [comment]
Try it with a brand new file just in case. Can I ask what your default encoding is on your machine? I would like to write a JUnit test that can account for this, but I can't replicate it.

**Comment by 404forever1** [comment]
C:\Users\Administrator>chcp
活动代码页: 936

C:\Users\Administrator>

**Comment by 404forever1** [comment]
> Try it with a brand new file just in case. Can I ask what your default encoding is on your machine? I would like to write a JUnit test that can account for this, but I can't replicate it.

Has the new file been uploaded to maven?

**Comment by tchristofferson** [comment]
Issue should be resolved. Spigot 1.8 configuration api doesn't use utf8 for GBK, as an example. Used SnakeYaml directly instead of the Spigot api since SnakeYaml allows me to explicitly use UTF8. Let me know if you find any other issues.
