### ISSUE TITLE
Problem with Unicode Characters

### ISSUE THREAD

**Issue by CroaBeast** [tchristofferson/Config-Updater#9]
Hi, I was using this resource in one plugin that I'm working on it, but it has issues with unicode.
My resource before compiling: [`Click Here`](https://prnt.sc/1siytfl)
After compiling: [`Click Here`](https://prnt.sc/1sizb79)

**Comment by tchristofferson** [comment]
This is a Spigot issue. In onEnable I saved the default config and called saveConfig method and this issue occurred. I didn't use ConfigUpdater to modify the config. Perhaps something doesn't work with UTF-8?
